#provide color macro for message function
macro(define_colors)
  if(WIN32 OR UNIX)
    # has no effect on WIN32
    string(ASCII 27 Esc)
    set(C_ColourReset "${Esc}[m")
    set(C_ColourBold "${Esc}[1m")
    set(C_Red "${Esc}[31m")
    set(C_Green "${Esc}[32m")
    set(C_Yellow "${Esc}[33m")
    set(C_Blue "${Esc}[34m")
    set(C_Magenta "${Esc}[35m")
    set(C_Cyan "${Esc}[36m")
    set(C_White "${Esc}[37m")
    set(C_BoldRed "${Esc}[1;31m")
    set(C_BoldGreen "${Esc}[1;32m")
    set(C_BoldYellow "${Esc}[1;33m")
    set(C_BoldBlue "${Esc}[1;34m")
    set(C_BoldMagenta "${Esc}[1;35m")
    set(C_BoldCyan "${Esc}[1;36m")
    set(C_BoldWhite "${Esc}[1;37m")
    
  else()
    set(C_ColourReset "")
    set(C_ColourBold "")
    set(C_Red "")
    set(C_Green "")
    set(C_Yellow "")
    set(C_Blue "")
    set(C_Magenta "")
    set(C_Cyan "")
    set(C_White "")
    set(C_BoldRed "")
    set(C_BoldGreen "")
    set(C_BoldYellow "")
    set(C_BoldBlue "")
    set(C_BoldMagenta "")
    set(C_BoldCyan "")
    set(C_BoldWhite "")
  endif()
endmacro()
define_colors()

set(color_cmake ${cmake_center}/color.cmake CACHE STRING "xxx")
#需要加上参数判断
function(log_d agv)
include(${color_cmake})
define_colors()
get_filename_component(pathdd ${CMAKE_CURRENT_LIST_FILE} NAME)
set(log_info "${C_BoldGreen}[${C_BoldWhite}DBUG${C_Magenta}|${C_White}${CMAKE_CURRENT_LIST_FILE}${C_BoldGreen}]${C_Magenta}:${C_White}\n")
message( "${log_info}${ARGV}")
endfunction(log_d agv)

function(log_i agv)
include(${color_cmake})
define_colors()
get_filename_component(pathdd ${CMAKE_CURRENT_LIST_FILE} NAME)
set(log_info "${C_BoldGreen}[${C_BoldWhite}INFO${C_BoldGreen}]${C_Magenta}:${C_White}")
message( "${log_info}${ARGV}")
endfunction(log_i )

function(log_t agv)
include(${color_cmake})
define_colors()
get_filename_component(pathdd ${CMAKE_CURRENT_LIST_FILE} NAME)
set(log_info "${C_BoldGreen}[${C_BoldWhite}EXTR${C_BoldGreen}]${C_Magenta}:${C_White}")
message( "${log_info}${ARGV}")
endfunction(log_t )


# function(log_base tag tag_color bracket_color)
# # include(./script/cmake/color.cmake)
# # define_colors()
# set(log_info "${bracket_color}[${tag_color}${tag}${bracket_color}]${bracket_color}:${C_White}")
# set(list_agv ${ARGV})
# list( POP_FRONT list_agv)
# list( POP_FRONT list_agv)
# # list( POP_FRONT list_agv)
# message( "${log_info}${list_agv}")
# endfunction()




