macro(define_var v_name value_default)
    if(NOT DEFINED ${v_name})
        log_i("not defined ${v_name}, set by default[${value_default}]")
        set(${v_name} ${value_default} CACHE STRING "xx")
    endif()
    log_i("defined ${v_name}=${${v_name}}")
endmacro()

macro(list_unique __lst)
  if(${__lst})
    list(REMOVE_DUPLICATES ${__lst})
  endif()
endmacro()

#SP_INC
#SP_LIB
#SP_SRC
#generate_module(ffmpeg SP_INC xx xx SP_LIB xx xx SP_SRC xxx xxx)
macro(generate_module module_name)
    set(temp_list ${ARGN})
    set(tag_ "")
    foreach(item_ ${temp_list})
        if(${item_} STREQUAL SP_INC)
            set(tag_ module_${module_name}_inc)
        elseif(${item_} STREQUAL SP_LIB)
            set(tag_ module_${module_name}_lib)
        elseif(${item_} STREQUAL SP_SRC)
            set(tag_ module_${module_name}_src)
        else()
            if(NOT ${item_} STREQUAL "NON")
                list(APPEND ${tag_} "${item_}")
            endif()
        endif()        
    endforeach()
    unset(tag_)
    list_unique(module_${module_name}_inc)
    list_unique(module_${module_name}_lib)
    list_unique(module_${module_name}_src)
    set(module_${module_name}_inc ${module_${module_name}_inc} CACHE STRING "xxx")
    set(module_${module_name}_lib ${module_${module_name}_lib} CACHE STRING "xxx")
    set(module_${module_name}_src ${module_${module_name}_src} CACHE STRING "xxx")
endmacro()

function(print_module module_name)
    if(DEFINED module_${module_name}_inc AND NOT module_${module_name}_inc STREQUAL "")
        log_t("module_${module_name}_inc=${module_${module_name}_inc}")
    else()
        log_t("module_${module_name}_lib=${C_Red}null")
    endif()

    if(DEFINED module_${module_name}_lib AND NOT module_${module_name}_lib STREQUAL "")
        log_t("module_${module_name}_lib=${module_${module_name}_lib}")
    else()
        log_t("module_${module_name}_lib=${C_Red}null")
    endif()

    if(DEFINED module_${module_name}_src AND NOT module_${module_name}_src STREQUAL "")
        log_t("module_${module_name}_src=${module_${module_name}_src}")
    else()
        log_t("module_${module_name}_src=${C_Red}null")
    endif()
    message("")
endfunction()


macro(add_module t_name module_name )
    target_link_libraries(${t_name} PRIVATE ${module_${module_name}_lib})
    target_include_directories(${t_name} PRIVATE ${module_${module_name}_inc})
    target_sources(${t_name} PRIVATE ${module_${module_name}_src})
endmacro()
